/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.co.indocyber.view;

import id.co.indocyber.controller.AdminController;
import id.co.indocyber.controller.SoalController;
import id.co.indocyber.model.Category;
import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class PlayGame extends javax.swing.JFrame {

    /**
     * Creates new form PlayGame
     */
    private SoalController soal;

    public PlayGame() {
        initComponents();
        hideStart();
        defaultValue();
        packing();

    }

    private void hideStart() {
        soalTxtField.setVisible(false);
        hintlbl.setVisible(false);
        hintLabel.setVisible(false);
        hintBtn.setVisible(false);
        jawabanTxtField.setVisible(false);
        youranswerLabel.setVisible(false);
        cekBtn.setVisible(false);
//        categoryCombo.setEnabled(false);
    }

    private void showStart() {
        soalTxtField.setVisible(true);
        hintlbl.setVisible(true);
        hintLabel.setVisible(true);
        hintBtn.setVisible(true);
        jawabanTxtField.setVisible(true);
        youranswerLabel.setVisible(true);
        cekBtn.setVisible(true);
//        categoryCombo.setEnabled(true);
    }

    private void defaultValue() {
        soalTxtField.setText("");
        hintLabel.setText("");
        jawabanTxtField.setText("");
    }

    private ComboBoxModel getCategoryModel() {
        DefaultComboBoxModel defaultCombo = new DefaultComboBoxModel();

        SoalController s = new SoalController();
        List<Category> cat = s.getCategory();

        for (Category category : cat) {
            defaultCombo.addElement(category.getCategoryName());
        }

        return defaultCombo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminForm = new javax.swing.JDialog();
        userTxtField = new javax.swing.JTextField();
        passTxtField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        adminHome = new javax.swing.JDialog();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        newCategoryBtn = new javax.swing.JButton();
        editCategoryBtn = new javax.swing.JButton();
        deleteCategoryBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        categoryTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        soalTable = new javax.swing.JTable();
        addSoalBtn = new javax.swing.JButton();
        editSoalBtn = new javax.swing.JButton();
        deleteSoalBtn = new javax.swing.JButton();
        categoryForm = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        categoryTxtField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        categorySaveBtn = new javax.swing.JButton();
        categoryCancelBtn = new javax.swing.JButton();
        categoryTitleLabel = new javax.swing.JLabel();
        soalForm = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        soalTitleLabel = new javax.swing.JLabel();
        soalFormTxtField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        soalHintTxtField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        soalCategoryCmbBox = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        soalSaveBtn = new javax.swing.JButton();
        soalCancelBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        adminBtn = new javax.swing.JButton();
        startBtn = new javax.swing.JButton();
        categoryCombo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        soalTxtField = new javax.swing.JTextField();
        hintlbl = new javax.swing.JLabel();
        hintLabel = new javax.swing.JLabel();
        jawabanTxtField = new javax.swing.JTextField();
        hintBtn = new javax.swing.JButton();
        cekBtn = new javax.swing.JButton();
        youranswerLabel = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        adminForm.setTitle("Admin Area");
        adminForm.setMaximumSize(new java.awt.Dimension(300, 180));
        adminForm.setMinimumSize(new java.awt.Dimension(300, 180));

        jLabel5.setText("Username");

        jLabel6.setText("Password");

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/co/indocyber/assets/login.png"))); // NOI18N
        jButton4.setToolTipText("Login");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/co/indocyber/assets/cancel.png"))); // NOI18N

        javax.swing.GroupLayout adminFormLayout = new javax.swing.GroupLayout(adminForm.getContentPane());
        adminForm.getContentPane().setLayout(adminFormLayout);
        adminFormLayout.setHorizontalGroup(
            adminFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(adminFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(adminFormLayout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(adminFormLayout.createSequentialGroup()
                        .addGroup(adminFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(55, 55, 55)
                        .addGroup(adminFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(userTxtField)
                            .addComponent(passTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        adminFormLayout.setVerticalGroup(
            adminFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminFormLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(adminFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(adminFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(10, 10, 10)
                .addGroup(adminFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        adminHome.setTitle("Master Data");
        adminHome.setMinimumSize(new java.awt.Dimension(600, 400));

        newCategoryBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/co/indocyber/assets/add_icon.png"))); // NOI18N
        newCategoryBtn.setToolTipText("New");
        newCategoryBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.lightGray, null, null));
        newCategoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCategoryBtnActionPerformed(evt);
            }
        });

        editCategoryBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/co/indocyber/assets/edit_icon.png"))); // NOI18N
        editCategoryBtn.setToolTipText("Edit");
        editCategoryBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.gray, null, null));
        editCategoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCategoryBtnActionPerformed(evt);
            }
        });

        deleteCategoryBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/co/indocyber/assets/delete_icon.png"))); // NOI18N
        deleteCategoryBtn.setToolTipText("Delete");
        deleteCategoryBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.gray, null, null));

        categoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Category ID", "Category Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(categoryTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(newCategoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editCategoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteCategoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 93, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editCategoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newCategoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteCategoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSplitPane1.setLeftComponent(jPanel2);

        jPanel3.setPreferredSize(new java.awt.Dimension(100, 436));

        soalTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Soal ID", "Soal", "Hint", "Category ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(soalTable);

        addSoalBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/co/indocyber/assets/add_icon.png"))); // NOI18N
        addSoalBtn.setToolTipText("New");
        addSoalBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.gray, null, null));
        addSoalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSoalBtnActionPerformed(evt);
            }
        });

        editSoalBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/co/indocyber/assets/edit_icon.png"))); // NOI18N
        editSoalBtn.setToolTipText("Edit");
        editSoalBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.gray, null, null));
        editSoalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editSoalBtnActionPerformed(evt);
            }
        });

        deleteSoalBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/co/indocyber/assets/delete_icon.png"))); // NOI18N
        deleteSoalBtn.setToolTipText("Delete");
        deleteSoalBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.gray, null, null));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(addSoalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editSoalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteSoalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addSoalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editSoalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteSoalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSplitPane1.setRightComponent(jPanel3);

        javax.swing.GroupLayout adminHomeLayout = new javax.swing.GroupLayout(adminHome.getContentPane());
        adminHome.getContentPane().setLayout(adminHomeLayout);
        adminHomeLayout.setHorizontalGroup(
            adminHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
        );
        adminHomeLayout.setVerticalGroup(
            adminHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        categoryForm.setMinimumSize(new java.awt.Dimension(300, 230));

        jLabel2.setText("Category Name:");

        categorySaveBtn.setText("Save");

        categoryCancelBtn.setText("Cancel");

        categoryTitleLabel.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        categoryTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        categoryTitleLabel.setText("jLabel3");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(categoryTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(categoryTxtField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 103, Short.MAX_VALUE)
                        .addComponent(categoryCancelBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(categorySaveBtn))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(categoryTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(categoryTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoryCancelBtn)
                    .addComponent(categorySaveBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout categoryFormLayout = new javax.swing.GroupLayout(categoryForm.getContentPane());
        categoryForm.getContentPane().setLayout(categoryFormLayout);
        categoryFormLayout.setHorizontalGroup(
            categoryFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        categoryFormLayout.setVerticalGroup(
            categoryFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        soalForm.setMinimumSize(new java.awt.Dimension(370, 300));

        soalTitleLabel.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 24)); // NOI18N
        soalTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        soalTitleLabel.setText("jLabel3");

        jLabel7.setText("Soal");

        jLabel8.setText("Hint");

        jLabel9.setText("Category");

        soalSaveBtn.setText("Save");

        soalCancelBtn.setText("Cancel");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(soalTitleLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(57, 57, 57)
                        .addComponent(soalFormTxtField))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(soalHintTxtField)
                            .addComponent(soalCategoryCmbBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 179, Short.MAX_VALUE)
                        .addComponent(soalCancelBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(soalSaveBtn)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(soalTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(soalFormTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(soalHintTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(soalCategoryCmbBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(soalSaveBtn)
                    .addComponent(soalCancelBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout soalFormLayout = new javax.swing.GroupLayout(soalForm.getContentPane());
        soalForm.getContentPane().setLayout(soalFormLayout);
        soalFormLayout.setHorizontalGroup(
            soalFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        soalFormLayout.setVerticalGroup(
            soalFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GUESSING GAME APP");
        setMaximumSize(new java.awt.Dimension(585, 310));
        setMinimumSize(new java.awt.Dimension(585, 0));
        setResizable(false);

        jPanel1.setLayout(null);

        adminBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/co/indocyber/assets/user.png"))); // NOI18N
        adminBtn.setToolTipText("Sign In Admin");
        adminBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        adminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminBtnActionPerformed(evt);
            }
        });
        jPanel1.add(adminBtn);
        adminBtn.setBounds(545, 11, 22, 19);

        startBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/co/indocyber/assets/start.png"))); // NOI18N
        startBtn.setToolTipText("START GAME");
        startBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startBtnActionPerformed(evt);
            }
        });
        jPanel1.add(startBtn);
        startBtn.setBounds(10, 11, 64, 69);

        categoryCombo.setModel(getCategoryModel());
        categoryCombo.setToolTipText("Select Category");
        jPanel1.add(categoryCombo);
        categoryCombo.setBounds(203, 60, 230, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("----------------- SELECT CATEGORY ---------------");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(180, 40, 290, 15);

        soalTxtField.setEditable(false);
        soalTxtField.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        soalTxtField.setText("SOAL");
        soalTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soalTxtFieldActionPerformed(evt);
            }
        });
        jPanel1.add(soalTxtField);
        soalTxtField.setBounds(108, 98, 430, 49);

        hintlbl.setText("HINT:");
        jPanel1.add(hintlbl);
        hintlbl.setBounds(108, 153, 28, 14);

        hintLabel.setText("jLabel3");
        jPanel1.add(hintLabel);
        hintLabel.setBounds(142, 153, 352, 14);
        jPanel1.add(jawabanTxtField);
        jawabanTxtField.setBounds(108, 202, 386, 20);

        hintBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/co/indocyber/assets/hint.png"))); // NOI18N
        hintBtn.setToolTipText("Hint");
        hintBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hintBtnActionPerformed(evt);
            }
        });
        jPanel1.add(hintBtn);
        hintBtn.setBounds(108, 240, 61, 69);

        cekBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/co/indocyber/assets/cek.png"))); // NOI18N
        cekBtn.setToolTipText("Cek Answer");
        cekBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekBtnActionPerformed(evt);
            }
        });
        jPanel1.add(cekBtn);
        cekBtn.setBounds(432, 240, 62, 69);

        youranswerLabel.setText("Your Answer");
        jPanel1.add(youranswerLabel);
        youranswerLabel.setBounds(10, 205, 61, 14);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/co/indocyber/assets/info.png"))); // NOI18N
        jButton6.setToolTipText("About This Game");
        jPanel1.add(jButton6);
        jButton6.setBounds(520, 10, 20, 20);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/co/indocyber/assets/help.png"))); // NOI18N
        jButton7.setToolTipText("How To Play");
        jPanel1.add(jButton7);
        jButton7.setBounds(500, 10, 20, 20);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/co/indocyber/assets/wallpaper.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(-80, -60, 660, 390);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void soalTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soalTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soalTxtFieldActionPerformed

    private void packing() {
        this.pack();
    }

    private void adminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminBtnActionPerformed
        // TODO add your handling code here:
        adminForm.setVisible(true);
    }//GEN-LAST:event_adminBtnActionPerformed

    private void startBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startBtnActionPerformed
        // TODO add your handling code here:
        showStart();
        packing();
//        startBtn.setEnabled(false);
        categoryCombo.setEnabled(false);
        String cat = String.valueOf(categoryCombo.getSelectedItem());
//        soal.generateSoal();
        soal = new SoalController(cat);
        soalTxtField.setText(soal.generateSoal());

    }//GEN-LAST:event_startBtnActionPerformed

    private void hintBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hintBtnActionPerformed
        // TODO add your handling code here:
        hintLabel.setText(soal.getHintSoal());
    }//GEN-LAST:event_hintBtnActionPerformed

    private void cekBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cekBtnActionPerformed
        // TODO add your handling code here:
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Are you sure about your answer", "Confirm", dialogButton);
        String answer = jawabanTxtField.getText();
        soal.setJawaban(answer);
        if (dialogResult == 0) {

            if (soal.cekJawaban()) {
                JOptionPane.showMessageDialog(rootPane, "Selamat jawaban anda benar");
                hideStart();
                categoryCombo.setEnabled(true);
                defaultValue();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Jawaban anda salah, silakan coba lagi");
                jawabanTxtField.setText("");
                jawabanTxtField.requestFocus();
            }
        } else {
            System.out.println("No thanks");
        }

    }//GEN-LAST:event_cekBtnActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        AdminController admin = new AdminController();
        boolean cek = admin.cekUser(userTxtField.getText(), passTxtField.getText());
        if(cek){
            adminForm.setVisible(false);
            adminHome.setVisible(true);
            userTxtField.setText("");
            passTxtField.setText("");
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Usernam atau Password salah, mohon cek kembali");
            userTxtField.setText("");
            passTxtField.setText("");
            userTxtField.requestFocus();
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void newCategoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCategoryBtnActionPerformed
        // TODO add your handling code here:
        categoryForm.setVisible(true);
        categoryForm.setTitle("New Category");
        categoryTitleLabel.setText("New Category");
    }//GEN-LAST:event_newCategoryBtnActionPerformed

    private void editCategoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCategoryBtnActionPerformed
        // TODO add your handling code here:
        categoryForm.setVisible(true);
        categoryForm.setTitle("Edit Category");
        categoryTitleLabel.setText("Edit Category");
    }//GEN-LAST:event_editCategoryBtnActionPerformed

    private void addSoalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSoalBtnActionPerformed
        // TODO add your handling code here:
        soalForm.setVisible(true);
        soalForm.setTitle("New Soal");
        soalTitleLabel.setText("New Soal");
    }//GEN-LAST:event_addSoalBtnActionPerformed

    private void editSoalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editSoalBtnActionPerformed
        // TODO add your handling code here:
        soalForm.setVisible(true);
        soalForm.setTitle("Edit Soal");
        soalTitleLabel.setText("Edit Soal");
    }//GEN-LAST:event_editSoalBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlayGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSoalBtn;
    private javax.swing.JButton adminBtn;
    private javax.swing.JDialog adminForm;
    private javax.swing.JDialog adminHome;
    private javax.swing.JButton categoryCancelBtn;
    private javax.swing.JComboBox<String> categoryCombo;
    private javax.swing.JDialog categoryForm;
    private javax.swing.JButton categorySaveBtn;
    private javax.swing.JTable categoryTable;
    private javax.swing.JLabel categoryTitleLabel;
    private javax.swing.JTextField categoryTxtField;
    private javax.swing.JButton cekBtn;
    private javax.swing.JButton deleteCategoryBtn;
    private javax.swing.JButton deleteSoalBtn;
    private javax.swing.JButton editCategoryBtn;
    private javax.swing.JButton editSoalBtn;
    private javax.swing.JButton hintBtn;
    private javax.swing.JLabel hintLabel;
    private javax.swing.JLabel hintlbl;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField jawabanTxtField;
    private javax.swing.JButton newCategoryBtn;
    private javax.swing.JTextField passTxtField;
    private javax.swing.JButton soalCancelBtn;
    private javax.swing.JComboBox<String> soalCategoryCmbBox;
    private javax.swing.JDialog soalForm;
    private javax.swing.JTextField soalFormTxtField;
    private javax.swing.JTextField soalHintTxtField;
    private javax.swing.JButton soalSaveBtn;
    private javax.swing.JTable soalTable;
    private javax.swing.JLabel soalTitleLabel;
    private javax.swing.JTextField soalTxtField;
    private javax.swing.JButton startBtn;
    private javax.swing.JTextField userTxtField;
    private javax.swing.JLabel youranswerLabel;
    // End of variables declaration//GEN-END:variables
}
